### ISSUE TITLE
Finalize persistence interface

### ISSUE THREAD

**Issue by krlmlr** [cynkra/dm#373]
- [x] double-check update: which SQL should be the default?
- [x] delete
- [x] truncate
- [x] patch
- [x] upsert
- [ ] FIXME
- [ ] tests

Follow-up to #319.

**Comment by TSchiefer** [comment]
- [ ] in line `op_results <- [...]` in rows-dm.R: tryCatch() and remember for which table(s) things failed in order to inform user precisely (cf. https://github.com/krlmlr/dm/pull/319#discussion_r430535867)
- [ ] think about a way to test if all `y`-columns are of the correct type?
- [ ] FIXMEs: bb019895fe03b01559c9cbec018c38371671b379 and 5ec9f20ceb8c60b56a3a7cef592e61532e67da9e

**Comment by krlmlr** [comment]
The persistence interface now lives in dbplyr, methods from there are used if they are available. No need to take action here.
